baseURL: 'https://blog.adityaone.com/'
languageCode: en-us
title: Aditya's
paginate: 5
theme: PaperMod
taxonomies:
    tag: tags
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
googleAnalytics: G-WJJJ4Z4MG2
minify:
    disableXML: true
    minifyOutput: true
params:
    env: production
    description: "Aditya's personal blog. Home of his thoughts, tutorials, and some wisdom 🤔"
    keywords: ["blog", "Aditya", "Vinodh", "technology", "ib", "cas", "programming", "tutorial"]
    mainSections: ["blog", "cas"]
    showReadingTime: true
    showToc: true
    ShowBreadCrumbs: true
    ShowPostNavLinks: true
    ShowCodeCopyButtons: true
    author: ["Aditya"]
    ShowShareButtons: true
    comments: true
    defaultTheme: auto
    assets:
            favicon: "favicon.ico"
            favicon16x16: "favicon-16x16.png"
            favicon32x32: "favicon-32x32.png"
            apple_touch_icon: "apple-touch-icon.png"
            favicon192x192: "favicon-192x192.png"
            favicon512x512: "favicon-512x512.png"
    homeInfoParams:
            Title: Hi there 👋
            Content: Welcome to my blog
    socialIcons:
            - name: "github"
              url: "https://github.com/adityavinodh"
            - name: "twitter"
              url: "https://twitter.com/THEadityavinodh"
            - name: "youtube"
              url: "https://www.youtube.com/channel/UCYlTq1cCFGL-tJgSw90TO0g"
            - name: "linkedin"
              url: "https://www.linkedin.com/in/adityavinodh/"
            - name: "instagram"
              url: "https://www.instagram.com/adityav5000/"
            - name: "stackoverflow"
              url: "https://stackoverflow.com/story/adityav"
            - name: "email"
              url: "mailto:aditya@adityaone.com"
            - name: "medium"
              url: "https://medium.com/@adityavinodh22"
            - name: "dev"
              url: "https://dev.to/adityavinodh"
outputs:
    home:
        - HTML
        - RSS
        - JSON
menu:
    main:
        - identifier: tags
          name: Tags
          url: /tags/
        - identifier: cas
          name: CAS
          url: /cas/
          weight: 10
        - identifier: blog
          name: Blog
          url: /blog/
          weight: 20
        - identifier: archives
          name: Archives
          url: /archives/
          weigth: 40
        - identifier: search
          name: Search
          url: /archive
          weigth: 50
