baseURL: 'https://yo.adityaone.com/'
languageCode: en-us
title: Aditya's
theme: PaperMod
params:
    mainSections: ["blog", "cas"]
    showReadingTime: true
    showToc: true
    ShowBreadCrumbs: true
    ShowPostNavLinks: true
    ShowCodeCopyButtons: true
    author: ["Aditya"]
    ShowShareButtons: true
    comments: true
    defaultTheme: auto
    homeInfoParams:
            Title: Hi there 👋
            Content: Welcome to my blog
    socialIcons:
            - name: "github"
              url: "https://github.com/adityavinodh"
            - name: "twitter"
              url: "https://twitter.com/THEadityavinodh"
            - name: "youtube"
              url: "https://www.youtube.com/channel/UCYlTq1cCFGL-tJgSw90TO0g"
            - name: "linkedin"
              url: "https://www.linkedin.com/in/adityavinodh/"
            - name: "instagram"
              url: "https://www.instagram.com/adityav5000/"
            - name: "stackoverflow"
              url: "https://stackoverflow.com/story/adityav"
            - name: "email"
              url: "mailto:aditya@adityaone.com"
            - name: "medium"
              url: "https://medium.com/@adityavinodh22"
            - name: "dev"
              url: "https://dev.to/adityavinodh"
outputs:
    home:
        - HTML
        - RSS
        - JSON
menu:
    main:
        - identifier: tags
          name: Tags
          url: /tags/
        - identifier: cas
          name: CAS
          url: /cas/
          weight: 10
        - identifier: blog
          name: Blog
          url: /blog/
          weight: 20
        - identifier: archives
          name: Archives
          url: /archives/
          weigth: 40
        - identifier: search
          name: Search
          url: /archive
          weigth: 50
